export TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER=yes
tezos-client --endpoint https://hangzhounet.api.tez.ie config update
export COCO_ADDRESS=tz1PARwN2EZW2i19xpWVmZK7viT83dq96dfd
export BOB_ADDRESS=tz1LsGys5zAgomRYxoTcsa7RWKfECVjPpSmp
export DAVID_ADDRESS=tz1etxmH6mjEW1ua1NFNBGSVWXvH47V2fbQc